# Generated by Django 3.0.4 on 2020-03-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Food', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
